name: tp_symfony
recipe: symfony
config:
  webroot: public
services:
  database:
    type: mysql
    portforward: 3313
    creds:
      user: admin
      password: admin
      database: camping
  node:
    type: node:14
    build:
      - yarn install
      - npm install
tooling:
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node



